apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loginbbs-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: civilraje.xyz
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loginbbs-service
            port:
              number: 80