
apiVersion: v1
kind: Service
metadata:
  name: loginbbs-service
spec:
  type: NodePort
  selector:
    app: loginbbs
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
